Generator/Models/ErrorViewModel.cs
namespace Generator.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Generator/Controllers/GenController.cs
using Generator.Implementations;
using Generator.Interfaces;
using Generator.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Monitoring.Models;
using System.Diagnostics;

namespace Generator.Controllers
{
    public class GenController : Controller
    {
        private readonly ILogger<GenController> _logger;
        
        public GenController(ILogger<GenController> logger)
        {
            _logger = logger;
        }
        public string area;
        [HttpPost]
        public IActionResult DiAreaAdd(string areaStr)
        {
            area = areaStr;
            return Redirect("/");
        }
        
        public IActionResult Download()
        {
            DownloadFile.Download(@"data.json");
            return Redirect("/");
        }
        public IActionResult SourceButton()
        {
            AreaSource.AddSource("adadaad");
            return Redirect("/");
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Help()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new Monitoring.Models.ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Generator/Controllers/HomeController.cs
using Generator.Implementations;
using Generator.Interfaces;
using Generator.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Generator.Controllers
{
    [Route("Generator")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult SourceButton()
        {
            AreaSource.AddSource("adadadddada");
            return Redirect("/");
        }
        //filePath();
        [Route("IndexGenerator")]
        public IActionResult Index()
        {
            return View();
        }
        [Route("HelpGenerator")]
        public IActionResult Help()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Generator/Views/Gen/Help.cshtml
@{
    ViewData["Title"] = "Help";
}
<h1>@ViewData["Title"]</h1>

<p>Эта страница позволяет скачать данные технологического процесса (генерируя их в фоне).</p>

Generator/Views/Gen/Index.cshtml
@{
    ViewData["Title"] = "Generator";
}

<div>
    <form method="post" asp-controller="Gen" asp-action="SourceButton" class="align-self-center">
        <input type="submit" class="mb-3 btn-primary" value="Изменить area" />
    </form>
</div>
<div>
    <form method="post" asp-controller="Gen" asp-action="Download" class="align-self-center">
        <input type="submit" class="mb-3 btn-primary" value="Download" />
    </form>
</div>
<div class="align-self-end" role="group" aria-label="task-actions">
    <button type="button" class="mb-3 btn-primary" data-bs-toggle="modal" data-bs-target="#AreaAdd">Добавить диарею</button>
</div>
<div class="modal fade mb-3" id="AreaAdd" tabindex="-1" aria-hidden="true" aria-labeledby="AreaAddLabel">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header mb-3">
                <h1 class="modal-title fs-5" id="AreaAddLabel">Добавить арею</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-controller="Gen" asp-action="DiAddArea">
                <input name="name" class="form-control mb-3" placeholder="Имя" />
                <input type="submit" class="mb-3 btn-primary" value="Принять" />
            </form>

        </div>
    </div>
</div>

Generator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Generator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Generator.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Gen" asp-action="Index">Generator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gen" asp-action="Index">Gen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gen" asp-action="Help">Help</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Generator - <a asp-area="" asp-controller="Gen" asp-action="Help">Help</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>